CREATE DATABASE ELECTRIC_MANAGER
GO

USE ELECTRIC_MANAGER

CREATE TABLE Meter(

	_METER_ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	_METER_COUNT FLOAT DEFAULT 0
)
	
GO
CREATE TABLE Customer (

	_CUSTOMER_ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	_CUSTOMER_NAME NVARCHAR(200) NOT NULL,
	_CUSTOMER_PHONE  NVARCHAR(11) NOT NULL,
	_CUSTOMER_KIND VARCHAR(50) DEFAULT 'ca nhan',
	_CUSTOMER_ADDRESS NVARCHAR(200) NOT NULL,
	_METER_ID INT FOREIGN KEY REFERENCES Meter(_METER_ID)

)

GO



